- ONECore/Classes/Utilities/FormValidation/Rules/IndonesianPhoneRule.swift
- ONECore/Classes/Utilities/FormValidation/Rules/InternationalPhoneRule.swift
None.
Cannot input phone number more than 13 digits
Change maximum phone number be 14 digits
None.
None.
None.
None.
> Fix: update maximum phone number

- ONECore/Classes/Utilities/Deeplink/StaticDeeplink.swift
None.
Create generic function for open other apps
None
None.
None.
None.
None.
> add function for open other apps

- Example/ONECore.xcodeproj/project.pbxproj
- ONECore.podspec
None.
`pod lib lint` hit an error.
Switch sign in into `Manual`.
None.
None.
None.
Bump version into `0.2.0`.
> Fix: Pod Lib Lint Error

- ONECore/Classes/Views/Label/Label.swift
- ONECore/Classes/Views/PinInput/PinInputView.swift
None.
Create new function, in label component for highlited text
None.
None.
None.
None.
None.
> improve label function

- ONECore/Classes/ViewControllers/NavigationController/NavigationController.swift
None.
Overlapping between remove and present action.
Delay the remove action.
None.
None.
None.
None.
> Fix: Remove Previous Controller

- ONECore.podspec
None.
None.
None.
None.
None.
None.
None.
> bump version from 0.2.0 to 0.3.0

- ONECore/Classes/Extensions/FormTableViewController+UITextField.swift
- ONECore/Classes/Helpers/SizeHelper.swift
- ONECore/Classes/Utilities/FormValidation/Rules/IndonesianPhoneRule.swift
- ONECore/Classes/ViewControllers/CameraViewController/CameraViewController+Gallery.swift
- ONECore/Classes/ViewControllers/ContactViewController/Coordinator/ContactCoordinator.swift
- ONECore/Classes/Views/ImageSelectionInput/ImageSelectionInputViewModel.swift
None.
None.
None.
None.
None.
None.
None.
> Feature: Enhance checkbox

- Example/Podfile.lock
- ONECore/Classes/Constants/DefaultValue.swift
- ONECore/Classes/Views/CheckboxView/CheckboxView.swift
- ONECore/Classes/Views/CheckboxView/Styles/CheckboxStyle.swift
- ONECore/Classes/Views/CheckboxView/Styles/DefaultCheckboxStyle.swift
- ONECore/Classes/Views/CollectionView/CollectionView.swift
- ONECore/Classes/Views/Label/Label.swift
None.
None.
- Add page control in colectionview
- Add highlighted text in checkboxview
None.
None.
None.
None.
> Feature: enhance checkbox view

- ONECore/Classes/ViewControllers/TableViewController/TableViewController.swift
None.
Dynamic footer view in table view controller.
Create `footerView` in `TableViewController` and you can set through setFooterView method.
None.
None.
None.
None.
> Feature: Footer View in Table View Controller

- Example/Tests/Extensions/Date+ExtensionTest.swift
- ONECore/Classes/Constants/DateFormat.swift
- ONECore/Classes/Extensions/Date+Extension.swift
None.
Need format date in "dd MMMM YYYY HH:mm"
Add function to handle format date in "dd MMMM YYYY HH:mm "
None.
None.
None.
None.
> add date format for day with time

- Example/Podfile.lock
- Example/Tests/Extensions/String+FormatTest.swift
- ONECore/Classes/Extensions/String+Format.swift
- ONECore/Classes/ViewControllers/TableViewController/TableViewController.swift
- ONECore/Classes/Views/CheckboxView/CheckboxView.swift
- ONECore/Classes/Views/CollectionView/CollectionView.swift
- ONECore/Classes/Views/Label/Label.swift
None.
Append character as a string prefix to get the specific text length.
Create `appendLeading` method as a string extension.
None.
None.
None.
Fix linter warning.
> Feature: Create Method to Append Prefix on String

- ONECore/Classes/Constants/DateFormat.swift
- ONECore/Classes/Extensions/Date+Extension.swift
None.
- New db date format
- Add `dbDateTime` & `year`
- add `dayMonthTime`
None.
None.
None.
None.
> Chore: add date format

- Example/Tests/Extensions/Date+ExtensionTest.swift
- Example/Tests/Extensions/String+DateTest.swift
- ONECore/Classes/Constants/DateFormat.swift
- ONECore/Classes/Extensions/Date+Extension.swift
- ONECore/Classes/Extensions/String+Date.swift
None.
- New db date format
- Add `shortDate` format
- Add unit test for `shortDate` format
None.
None.
None.
None.
> Feature: Add date format

- ONECore.podspec
Release Notes:
- Add new DateFormat + Extension.
- Create appendLeading method as a String extension.
- Declare setupViewModel method in TableViewController.
> bump version from 0.5.0 to 0.6.0

- ONECore/Classes/Views/View/View.swift
None.
when set gradient color to view that has already has gradient color, it wont change the gradient color.
remove the gradient layer first and re-add the layer (manually)
None.
None.
None.
None.
> add method to remove gradient in view

- ONECore.podspec
None.
None.
None.
None.
None.
None.
None.
> bump version from 0.6.0 to 0.7.0

- ONECore/Classes/Views/PickerView/Styles/TimeDatePickerStyle.swift
- ONECore/Classes/Views/TextField/Types/InputType.swift
- ONECore/Classes/Views/TextField/Types/TimePickerInputType.swift
None.
None.
- Support TimeInputType
None.
None.
None.
None.
> Feature: TimePickerInputType

- ONECore.podspec
None.
Add Feature TimePickerInputType
None.
None.
None.
None.
None.
> bump version from 0.7.0 to 0.8.0

- Example/Podfile.lock
- Example/Tests/Extensions/Date+ExtensionTest.swift
- ONECore/Classes/Constants/DateFormat.swift
- ONECore/Classes/Extensions/Date+Extension.swift
None.
add date format
None.
None.
None.
None.
None.
> Chore: add date and time

- ONECore/Classes/Constants/CoreConfig.swift
- ONECore/Classes/Extensions/Date+Extension.swift
None.
None.
- add language date core config
None.
None.
None.
None.
> chore: add date core config

- Example/ONECore.xcodeproj/project.pbxproj
- Example/ONECore/Services/Base/Service.swift
- Example/ONECore/Services/Base/ServiceSessionManager.swift
- Example/Podfile
- Example/Podfile.lock
- Example/Tests/Helpers/NavigationHelperTest.swift
- ONECore.podspec
- ONECore/Classes/Views/View/View.swift
None.
- need to update Alamofire and objectMapper to satisfy the ONEOnboard requirement for  byon
- need to update minimun ios deployment version to be able to update Alamofire and objectMapper
- update minimum deployment ios to 10.0
- update Alamofire to  (5.0.0-rc.2)
- update AlamofireObjectMapper to (6.2.0)
None.
None.
None.
None.
> Feat: Update Library Version

- ONECore/Classes/Extensions/Date+Extension.swift
- ONECore/Classes/Helpers/DateHelper.swift
None.
- Remove time did not work because wrong language
- Changet language to coreconfig setting
None.
None.
None.
None.
> Fix: change language to coreconfig

- ONECore.podspec
bump version from 0.9.0 to 0.10.0
> bump version from 0.9.0 to 0.10.0

- ONECore.podspec
None.
None.
bump version to 0.11.0
None.
None.
None.
None.
> bump version from 0.10.0 to 0.11.0

- ONECore/Classes/Views/View/View.swift
None.
- Shadow layer overlapping after rerender
- remove shadowlayer before init new one
None.
None.
None.
None.
> Fix: Duplicate Shadow Layer

- ONECore/Classes/Extensions/FormTableViewController+UITextField.swift
None.
Need detect textfield when end editing and begin editing
Set "open" function didEndEditing and beginEditing textfield 
None.
None.
None.
None.
> open func textFieldDidBeginEditing & textFieldDidEndEditing

- Example/Tests/Extensions/Date+ExtensionTest.swift
- ONECore/Classes/Constants/DateFormat.swift
- ONECore/Classes/Extensions/Date+Extension.swift
None.
None.
- Add date with full month format
None.
None.
None.
None.
> Feature: Add new date format

- ONECore/Classes/Extensions/FormTableViewController+UITextField.swift
None.
None.
Change textfield delegate from public to open
None.
None.
None.
None.
> open func shoulchangecharacter

- ONECore.podspec
bump version from 0.13.0 to 0.13.1
> bump version from 0.13.0 to 0.13.1

- ONECore/Classes/Views/Button/Styles/ButtonStyle.swift
- ONECore/Classes/Views/Button/Styles/DefaultButtonStyle.swift
None.
None.
- Add indicator color to support iOS 13
None.
None.
None.
None.
> Chore: add indicator color

- ONECore/Classes/Extensions/Int+Extension.swift
None.
None.
- add positionalStyle
None.
None.
None.
None.
None
> Feature: add positionalStyle

- ONECore/Classes/Views/TextField/Types/TimePickerInputType.swift
https://ndv666.atlassian.net/browse/PK-2355
None.
- use wheels style for time picker
None.
None.
None.
None.
None.
> Chore: Update time picker

- ONECore/Classes/Views/CheckboxView/CheckboxView.swift
None.
- CheckView Breaking Constraint
- Fixing CheckView Breaking Constraint
None.
None.
None.
None.
* None
> [NO-JIRA] Chore: Fixing CheckboxView Breaking Constraint

- ONECore/Classes/Extensions/UIView+Extension.swift
> Feature: Save image

- ONECore.podspec
bump version from 0.16.0 to 0.17.0
> chore: bump version

- ONECore.podspec
None.
None.
Update podspec to swift 5
None.
None.
None.
None.
None.
> chore: update swift 5

- ONECore/Classes/ViewControllers/DropDownViewController/DropDownViewController.swift
None.
None.
- Add resetSearchKeyword
- change didChangeSearchKeyword to open
None.
None.
None.
None.
None.
> Feature: update dropdown
